# Deploy GitHub Pages using the official Pages actions.
# Set PUBLISH_DIR below to the directory that contains your index.html (e.g. "./", "docs", "build", "dist", "public").
# Trigger branch: change 'main' if your default branch is 'master' or something else.
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

env:
  # Change this to the directory that contains index.html
  PUBLISH_DIR: "./interactive-course/"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Optional build step — remove or replace if your site is pure HTML or uses a different build system.
      - name: Build site (optional)
        run: |
          echo "No build step defined. Add build commands here if you use a generator (npm run build, hugo, etc.)."

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ env.PUBLISH_DIR }}

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
